---
# Implementation references:
# N/A
- hosts: all
  become: yes
  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

    - name: Install Vagrant
      apt:
        name: vagrant
        state: present
        update_cache: yes
