---
# Implementation references:
#
# Unattended extension pack installation:
# https://www.reddit.com/r/ansible/comments/l1wof8/install_virtualboxextpack_accepting_the_eula/
- hosts: all
  become: yes
  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

    - name: Accept virtualbox-ext-pack select license
      debconf:
        name: virtualbox-ext-pack
        question: virtualbox-ext-pack/license
        value: 'true'
        vtype: select

    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - virtualbox
          - virtualbox-ext-pack
        update_cache: yes